# Generated by Django 5.2 on 2025-12-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_especificacion_especificacion_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacion',
            name='unidad_medida',
            field=models.CharField(default='glb', max_length=10, verbose_name='Unidad de Medida'),
        ),
    ]
