# Generated by Django 6.0.3 on 2026-03-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_especificacion_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacion',
            name='cantidad',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cantidad'),
        ),
    ]
