# Generated by Django 6.0.3 on 2026-03-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_refactor_especificacion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacion',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Mostrar'),
        ),
    ]
