# Generated by Django 6.0.3 on 2026-03-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_add_mostrar_to_especificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
    ]
