# Generated by Django 6.0.7 on 2026-07-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_backfill_proyecto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='solicitante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación'),
        ),
    ]
