# Generated by Django 6.0.7 on 2026-10-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_alter_proyecto_solicitante_alter_proyecto_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='objetivo',
            field=models.TextField(blank=True, help_text='Objetivo del proyecto para el pliego. Puede generarse con IA y editarse manualmente.', verbose_name='Objetivo'),
        ),
    ]
