# Generated by Django 6.0.3 on 2026-03-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubi_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='ciudad',
            field=models.CharField(max_length=255, verbose_name='Ciudad/Localidad'),
        ),
    ]
