# Generated by Django 6.0.7 on 2026-10-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubi_web', '0002_ciudad_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='ruta_distancia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Distancia desde el centro'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ruta_duracion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tiempo estimado'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ruta_resumen',
            field=models.TextField(blank=True, help_text='Resumen genérico del acceso desde el centro de la ciudad (generado automáticamente, editable).', verbose_name='Resumen de ruta'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ruta_vias',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vías principales'),
        ),
    ]
