# Generated by Django 6.0.3 on 2026-03-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0010_especificaciontecnica_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciontecnica',
            name='clasificacion',
            field=models.JSONField(blank=True, null=True, verbose_name='Clasificación'),
        ),
    ]
