# Generated by Django 6.0.3 on 2026-03-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0011_especificaciontecnica_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciontecnica',
            name='parametros_materiales',
            field=models.JSONField(blank=True, null=True, verbose_name='Parámetros Materiales'),
        ),
    ]
