# Generated by Django 6.0.3 on 2026-03-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0012_add_parametros_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciontecnica',
            name='criterios_calidad',
            field=models.JSONField(blank=True, null=True, verbose_name='Criterios de Calidad'),
        ),
        migrations.AddField(
            model_name='especificaciontecnica',
            name='normas_aplicables',
            field=models.JSONField(blank=True, null=True, verbose_name='Normas Aplicables'),
        ),
        migrations.AddField(
            model_name='especificaciontecnica',
            name='parametros_ejecucion',
            field=models.JSONField(blank=True, null=True, verbose_name='Parámetros Ejecución'),
        ),
    ]
