# Generated by Django 6.0.3 on 2026-03-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0013_add_parametros_ejecucion_normas_criterios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametros',
            old_name='detalle',
            new_name='descripcion',
        ),
    ]
