# Generated by Django 6.0.3 on 2026-03-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0014_rename_detalle_to_descripcion_parametros'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciontecnica',
            name='descripcion_mejorada',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Mejorada'),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
