# Generated by Django 6.0.3 on 2026-03-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0015_add_descripcion_mejorada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametros',
            name='especificacion_tecnica',
        ),
        migrations.AddField(
            model_name='especificaciontecnica',
            name='actividades_adicionales',
            field=models.JSONField(blank=True, null=True, verbose_name='Actividades Adicionales'),
        ),
        migrations.DeleteModel(
            name='ActividadesAdicionales',
        ),
        migrations.DeleteModel(
            name='Parametros',
        ),
    ]
