# Generated by Django 6.0.3 on 2026-03-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0016_add_actividades_json_remove_old_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificaciontecnica',
            name='descripcion_mejorada',
        ),
        migrations.AddField(
            model_name='especificaciontecnica',
            name='resumen',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen'),
        ),
    ]
