# Generated by Django 6.0.3 on 2026-03-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0017_rename_descripcion_mejorada_to_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciontecnica',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='especificaciontecnica',
            name='paso',
            field=models.IntegerField(default=0, verbose_name='Paso'),
        ),
    ]
