# Generated by Django 6.0.3 on 2026-03-17 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0019_add_proyecto_to_especificacion_tecnica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificaciontecnica',
            name='cantidad',
        ),
    ]
