# Generated by Django 6.0.4 on 2026-04-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0020_remove_cantidad_from_especificacion_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciontecnica',
            name='es_demo',
            field=models.BooleanField(default=False, verbose_name='Es Demo'),
        ),
    ]
