# Generated by Django 6.0.7 on 2026-07-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0021_add_es_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificaciontecnica',
            name='es_demo',
        ),
    ]
