# Generated by Django 6.0.7 on 2026-07-15 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_marca'),
        ('pliego_licitacion', '0023_especificaciontecnica_credito_consumido'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciontecnica',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa dueña de este dato, fijada al crearlo. Vacío = cuenta personal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especificaciones_tecnicas', to='accounts.empresa', verbose_name='Empresa'),
        ),
    ]
