# Generated by Django 6.0.7 on 2026-07-16 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pliego_licitacion', '0025_backfill_especificaciontecnica_empresa'),
        ('proyectos', '0010_alter_proyecto_solicitante_alter_proyecto_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciontecnica',
            name='especificacion_guardada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='proyectos.especificacion', verbose_name='Especificación guardada'),
        ),
    ]
