# Generated by Django 6.0.3 on 2026-03-17 05:19

import django.db.models.deletion
import servicios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=servicios.models.especificacion_upload_path)),
                ('unidad_medida', models.CharField(default='glb', max_length=10, verbose_name='Unidad de Medida')),
                ('cantidad', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cantidad')),
                ('actividades_adicionales', models.JSONField(blank=True, null=True, verbose_name='Actividades Adicionales')),
                ('mostrar', models.BooleanField(default=True, verbose_name='Mostrar')),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'servicios_especificacion',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacionImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=servicios.models.especificacion_imagen_upload_path)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('especificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicios.especificacion')),
            ],
            options={
                'verbose_name': 'Imagen de Especificación (Servicio)',
                'verbose_name_plural': 'Imágenes de Especificaciones (Servicios)',
                'db_table': 'servicios_especificacionimagen',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de Servicio')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Solicitante')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('publico', models.BooleanField(default=False, verbose_name='Público')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios_proyecto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='especificacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='servicios.proyecto'),
        ),
    ]
