# Generated by Django 6.0.3 on 2026-03-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_servicio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='objetivo',
            field=models.TextField(blank=True, verbose_name='Objetivo'),
        ),
    ]
