# Generated by Django 6.0.3 on 2026-03-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_catalogo_replace_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='alcance_editado',
            field=models.TextField(blank=True, verbose_name='Alcance editado por usuario'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='alcance_generado',
            field=models.TextField(blank=True, verbose_name='Alcance generado por IA'),
        ),
        migrations.AlterField(
            model_name='catalogoservicios',
            name='datos',
            field=models.JSONField(default=list, help_text='Lista de categorías. Estructura: [{"nombre": "...", "subcategorias": [{"codigo": "SM-01", "nombre": "...", "definicion": "...", "alcance": "...", "descripcion": "..."}]}]', verbose_name='Datos del catálogo'),
        ),
    ]
