# Generated by Django 6.0.7 on 2026-07-15 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_marca'),
        ('servicios', '0010_servicio_credito_consumido'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoservicios',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Vacío = catálogo global/base, usado por empresas sin catálogo propio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogos_servicios', to='accounts.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa dueña de este servicio, fijada al crearlo. Vacío = cuenta personal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='accounts.empresa', verbose_name='Empresa'),
        ),
    ]
