# Generated by Django 6.0.7 on 2026-07-13 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Apagado: se usa la configuración de correo del servidor (.env).', verbose_name='Usar esta configuración SMTP')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Servidor SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='Puerto')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Usuario')),
                ('password', models.CharField(blank=True, max_length=500, verbose_name='Contraseña')),
                ('from_email', models.CharField(blank=True, help_text='Ej. CEV <noreply@dominio>. Vacío = el del servidor.', max_length=255, verbose_name='Remitente')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de correo',
                'verbose_name_plural': 'Configuración de correo',
            },
        ),
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Dominio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('default_role', models.CharField(blank=True, choices=[('USUARIO', 'Usuario'), ('ADMINISTRADOR', 'Administrador')], help_text='Rol asignado a los usuarios de este dominio (Usuario si se deja vacío).', max_length=20, verbose_name='Rol por defecto')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dominio permitido',
                'verbose_name_plural': 'Dominios permitidos',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('default_role', models.CharField(blank=True, choices=[('USUARIO', 'Usuario'), ('ADMINISTRADOR', 'Administrador')], max_length=20, verbose_name='Rol por defecto')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correo permitido',
                'verbose_name_plural': 'Correos permitidos',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USUARIO', 'Usuario'), ('ADMINISTRADOR', 'Administrador')], default='USUARIO', max_length=20, verbose_name='Rol')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USUARIO', 'Usuario'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('capability', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Permisos de roles',
                'ordering': ['role', 'capability'],
                'unique_together': {('role', 'capability')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de usuario',
                'verbose_name_plural': 'Permisos de usuario',
                'ordering': ['user_id', 'capability'],
                'unique_together': {('user', 'capability')},
            },
        ),
    ]
