# Generated by Django 6.0.7 on 2026-07-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_empresa_y_creditos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='default_role',
        ),
    ]
