# Generated by Django 6.0.7 on 2026-07-14 04:59

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_empresa_default_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mostrado', models.CharField(blank=True, help_text='Cómo aparece el nombre en portada y pie. Vacío = el nombre de la cuenta.', max_length=120, verbose_name='Nombre en los documentos')),
                ('logo', models.ImageField(blank=True, help_text='Reemplaza el logo de la plantilla. PNG o JPG, fondo transparente si es posible.', null=True, upload_to=accounts.models.marca_upload_path, verbose_name='Logo')),
                ('color_primario', models.CharField(default='#1f2937', help_text='Títulos y encabezados de tabla en el documento. Formato #RRGGBB.', max_length=7, verbose_name='Color principal')),
                ('color_secundario', models.CharField(default='#6b7280', help_text='Subtítulos y detalles. Formato #RRGGBB.', max_length=7, verbose_name='Color secundario')),
                ('identificacion_fiscal', models.CharField(blank=True, max_length=40, verbose_name='NIT / RUT')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('sitio_web', models.CharField(blank=True, max_length=120, verbose_name='Sitio web')),
                ('pie_pagina', models.CharField(blank=True, help_text='Texto al pie de cada página del documento.', max_length=200, verbose_name='Pie de página')),
                ('plantilla_proyectos', models.FileField(blank=True, help_text='.docx propio para las especificaciones de proyectos.', null=True, upload_to=accounts.models.marca_upload_path, verbose_name='Plantilla Word — Proyectos')),
                ('plantilla_servicios', models.FileField(blank=True, help_text='.docx propio para las especificaciones de servicios.', null=True, upload_to=accounts.models.marca_upload_path, verbose_name='Plantilla Word — Servicios')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='accounts.empresa')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('empresa__isnull', False), ('usuario__isnull', True)), models.Q(('empresa__isnull', True), ('usuario__isnull', False)), _connector='OR'), name='marca_de_empresa_o_de_usuario')],
            },
        ),
    ]
