# Generated by Django 6.0.7 on 2026-10-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre_mostrado',
            field=models.CharField(blank=True, help_text='Cómo aparece el nombre en los documentos Word y en el pliego generado. Vacío = el nombre de la cuenta.', max_length=120, verbose_name='Nombre en los documentos'),
        ),
    ]
