# Generated by Django 6.0.4 on 2026-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Cliente', help_text='Aparece en las especificaciones generadas por IA (ej: "EMBOL S.A.", "Coca-Cola Embonor"). Por defecto: Cliente.', max_length=200, verbose_name='Nombre de empresa')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
