# Generated by Django 6.0.4 on 2026-04-20 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos_usados', models.PositiveSmallIntegerField(default=0)),
                ('fecha_primer_intento', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_trial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Trial',
                'verbose_name_plural': 'Demo Trials',
            },
        ),
    ]
