# Generated by Django 6.0.4 on 2026-04-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demotrial',
            name='max_intentos',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dejar vacío para usar el límite global (DEMO_MAX_TRIALS).', null=True, verbose_name='Máx. intentos'),
        ),
    ]
